#!/bin/bash

SCRIPT_VERSION="3.4-8"

TREE=${HOME}/.local/share/awl
PROGRAM=${TREE}/bin
PREFIX_UMU=${TREE}/pfx_umu
UMU_LOCATION=${TREE}/proton-umu

FLATPAK_LOCALFILES=${HOME}/.var/app
DOLPHIN_LOCATION=${FLATPAK_LOCALFILES}/org.DolphinEmu.dolphin-emu
PLAY_LOCATION=${FLATPAK_LOCALFILES}/org.purei.Play

function runGameTekno(){
	while true; do
		clear
		if [[ ! $(cat /etc/locale.gen | grep en_US.UTF-8 | tr -d '#') ]]; then
			printf "\e[1;93mWARNING:\e[0m You do NOT have en_US defined in your locale.gen, which may break some Lua games. Do you still wish to continue? "
			read -p "[Y/n] " userLocaleInput
			[[ -z $userLocaleInput ]] && userLocaleInput="y"
			if [[ $userLocaleInput == "Y" || $userLocaleInput == "y" ]]; then
				break
			elif [[ $userLocaleInput == "N" || $userLocaleInput == "n" ]]; then
				printf "For more information, see: https://github.com/sakaki91/Arcade.Wrapper-Linux/issues/2\n"
				exit
			else
				printf "\e[1;91mERROR:\e[0m Invalid option.\n"
				sleep 1.5
				clear
			fi
		else
			break
		fi
	done
	export LC_ALL=en_US.UTF-8
    export LC_NUMERIC=en_US.UTF-8
	export LANG=en_US.UTF-8
	GAMEID=0 PROTONPATH="$UMU_LOCATION" WINEPREFIX=$PREFIX_UMU umu-run $PROGRAM/TeknoParrotUi.exe
}

function runGameTriforce(){
	[[ ! $(command -v flatpak) ]] && printf "\e[1;91mERROR:\e[0m Flatpak not found.\n" && exit
	[[ ! "$(flatpak list | grep Dolphin)" ]] && printf "\e[1;91mERROR:\e[0m Emulator not found: Dolphin (Flatpak).\n" && exit
   	[[ ! -f "$DOLPHIN_LOCATION"/data/dolphin-emu/Triforce/segaboot.gcm ]] && printf "\e[1;91mERROR:\e[0m File not found: segaboot.gcm\n==> (https://github.com/sakaki91/Arcade.Wrapper-Linux/issues/7)\n" && exit
   	while true; do
 		DOLPHIN_ROM=$(zenity --file-selection --title="Select the desired ROM (Dolphin):" )
       	if [[ -z "$DOLPHIN_ROM" ]]; then
			printf "\e[1;91mERROR:\e[0m No rom selected.\nWould you like to try again?\n"
       	   	read -p "[Y/n] " zenityDecision
			if [[ "$zenityDecision" == "Y" || "$zenityDecision" == "y" ]]; then
       		    clear
        	elif [[ $zenityDecision == "N" || $zenityDecision == "n" ]]; then
       	       	break
	    	else
       	   		printf "\e[1;91mERROR:\e[0m Invalid option.\n"
    		fi
		fi
		[[ "$DOLPHIN_ROM" != "" ]] && flatpak run org.DolphinEmu.dolphin-emu "$DOLPHIN_ROM" && exit
	done
}

function runGameNamcoSys(){
	[[ ! "$(command -v flatpak)" ]] && printf "\e[1;91mERROR:\e[0m Flatpak not found.\n" && exit
	[[ ! "$(flatpak list | grep Play)" ]] && printf "\e[1;91mERROR:\e[0m Emulator not found: Play! (Flatpak).\n" && exit
	while true; do
        PLAY_ROM_DIR="$PLAY_LOCATION/config/Play Data Files/arcaderoms"
		[[ ! -d "$TREE"/play ]] && ln -sf "$PLAY_ROM_DIR" "$TREE"/play
        printf "\e[1;33mWARNING:\e[0m The dump files for the Play emulator games MUST be in this folder:\n($PLAY_ROM_DIR).\notherwise an error will occur due to emulator limitations.\nPress 'enter' to continue" && read
        PLAY_ROM_SELECTION=$(zenity --file-selection --directory --title="Select the desired ROM (Play, Folder only):")
	    if [[ -z "$PLAY_ROM_SELECTION" ]]; then
 			printf "\e[1;91mERROR:\e[0m No rom selected.\nWould you like to try again?\n"
       		read -p "[Y/n] " zenityDecision
       		if [[ $zenityDecision == "Y" || $zenityDecision == "y" ]]; then
            	clear
	        elif [[ $zenityDecision == "N" || $zenityDecision == "n" ]]; then
     		    break
      		else
	        	printf "\e[1;91mERROR:\e[0m Invalid option.\n" && exit
           	fi
		fi
		[[ "$PLAY_ROM_SELECTION" != "" ]] && PLAY_ROM=$(basename $PLAY_ROM_SELECTION) && flatpak run org.purei.Play --arcade "$PLAY_ROM" && exit
	done
}

clear
while true; do
	printf "awl-$SCRIPT_VERSION > " && read -p "" mainInput
	[[ $mainInput == "exit" ]] && printf "\e[0;92mEXIT_SUCCESS\e[0m\n" && exit
	if [[ -z $mainInput ]]; then
		:
	elif [[ $mainInput == "clear" ]]; then
		clear
	elif [[ $mainInput == "list" ]]; then
		[[ ! -f "$PROGRAM"/TeknoParrotUi.exe ]] && _teknoinstalled="\e[0;91m[NOT INSTALLED].\e[0m"
		[[ ! $(flatpak list | grep Dolphin) ]] && _dolphininstalled="\e[0;91m[NOT INSTALLED].\e[0m"
		[[ ! $(flatpak list | grep Play) ]] && _playinstalled="\e[0;91m[NOT INSTALLED].\e[0m"
		printf "%-15s %0s $_teknoinstalled%0s\n" "tekno" "TeknoParrot (via UMU-Proton)" ""
		printf "%-15s %0s $_dolphininstalled%0s\e[0m\n" "triforce" "Sega Triforce (Dolphin via Flatpak)" ""
		printf "%-15s %0s $_playinstalled%0s\e[0m\n" "namcosys" "Namco System 147/246 (Play! via Flatpak)" ""
	elif [[ $mainInput == "tekno" ]]; then
		runGameTekno
	elif [[ $mainInput == "triforce" ]]; then
		runGameTriforce
	elif [[ $mainInput == "namcosys" ]]; then
		runGameNamcoSys
	else
		printf "\e[0;91mERROR:\e[0m Invalid option.\n"
	fi
done
